### ISSUE TITLE
使用是出现的问题

### ISSUE THREAD

**Issue by zhaijian** [caobohua/ostar#1]
您好，我在使用类库时遇到以下问题：
1.go get时出现package qiniu/codec: unrecognized import path "qiniu/codec"问题；
2.服务端使用的是您的库，客户端是Android，如果客户端使用私钥加密生成字符串，服务器用该字符串公钥解密，能够正确解析；如果服务端使用私钥加密生成字符串，客户端用该字符串公钥解密，解析的字符串会出现乱码例如?????????????????????????????????????????????zmc，其中zmc是正确的字符串。

**Comment by zhaijian** [comment]
服务端私钥加密过程：
        public_key, _ := ReadBytes("public2048.pem")
    private_key, _ := ReadBytes("private2048.pem")
    codec.RSA.Init(public_key, private_key)
    test := ""
    md5 := ""
    content := "abcdefg"
    str, _ := codec.RSA.String(content, codec.MODE_PRIKEY_ENCRYPT)
    log.Println("@str ", test, " @rsa ", str)

**Comment by zhaijian** [comment]
客户端公钥解密过程：
public static byte[] decryptByPublicKey(byte[] data,Context context)throws Exception{
        InputStream inputStream = context.getResources().getAssets().open("rsa_public_key.pem");
        String key = readKey(inputStream);
        byte[] keyBytes = Base64.decode(key, Base64.DEFAULT);
        X509EncodedKeySpec x509EncodedKeySpec = new X509EncodedKeySpec(keyBytes);
        KeyFactory keyFactory = KeyFactory.getInstance(RSA);
        Key publicKey = keyFactory.generatePublic(x509EncodedKeySpec);
        //对数据解密
        Cipher cipher = Cipher.getInstance(keyFactory.getAlgorithm());
        cipher.init(Cipher.DECRYPT_MODE, publicKey);
        return cipher.doFinal(data);
    }
麻烦看下，谢谢！

**Comment by qyxing** [comment]
qiniu/codec
test_rsa.go把这里的引用改为ostar/codec即可, 非常抱歉， 上传的时候忘改路径了

在 2015年12月3日 下午5:57，zhaijian notifications@github.com写道：

**Comment by qyxing** [comment]
或者直接下载下来，放到go的src目录， 把当中的main.go和test_rsa.go删除即可

在 2015年12月3日 下午5:57，zhaijian notifications@github.com写道：

**Comment by qyxing** [comment]
执行这句codec.RSA.Init(public_key, private_key)里会有返回公钥和私钥是否为error,
 先打印下公钥和私钥格式是否有错。

下面是我的java类, 我现在就用的这个

package top.ostar.util;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.security.Key;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;

import javax.crypto.Cipher;

import org.apache.commons.codec.binary.Base64;
import org.apache.commons.io.IOUtils;

public class RSASecurity {
public enum Mode {
PUBKEY_ENCRYPT, //公钥加密
PUBKEY_DECRYPT, //公钥解密
PRIKEY_ENCRYPT, //私钥加密
PRIKEY_DECRYPT;  //私钥解密
}
public enum KeySize{
SIZE_1024(1024), SIZE_2048(2048), SIZE_768(768);
private int _value;
private KeySize(int value){
_value = value;
}
public int value(){
return _value;
}
}
private static final String getPublicKeyString(KeySize size) {
switch (size) {
case SIZE_1024:
return "MIGfMA0GCSqGSIb3D.......";
default:
return "MIIBIjANBgkqhkiG9.......";
}
}
private static final String getPrivateKeyString(KeySize size) {
switch (size) {
case SIZE_1024:
return "MIICdwIBADANB......";
default:
return "MIIEvgIBADANBgkqhkiG9w.....";
}
}

public static String exec(String data, Mode mode) throws Exception{
return exec(data, mode, KeySize.SIZE_2048);
}
public static String exec(String data, Mode mode, KeySize size) throws
Exception{
if(data == null){
return null;
}
if(mode == Mode.PUBKEY_ENCRYPT || mode == Mode.PRIKEY_ENCRYPT){
return Base64.encodeBase64String(exec(data.getBytes("UTF-8"), mode, size));
}else{
return new String(exec(Base64.decodeBase64(data), mode, size), "UTF-8");
}
}
public static byte[] exec(byte[] data, Mode mode) throws Exception{
return exec(data, mode, KeySize.SIZE_2048);
}
public static byte[] exec(byte[] data, Mode mode, KeySize size) throws
Exception{
if(data == null){
return null;
}
ByteArrayOutputStream baos = null;
ByteArrayInputStream bais = null;
try{
baos = new ByteArrayOutputStream();
bais = new ByteArrayInputStream(data);
exec(bais, baos, mode, size);
return baos.toByteArray();
}finally{
IOUtils.closeQuietly(baos);
IOUtils.closeQuietly(bais);
}
}
public static void exec(InputStream in, OutputStream os, Mode mode) throws
Exception{
exec(in, os, mode, KeySize.SIZE_2048);
}
public static void exec(InputStream in, OutputStream os, Mode mode, KeySize
size) throws Exception{
Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
switch (mode) {
case PUBKEY_ENCRYPT:
cipher.init(Cipher.ENCRYPT_MODE, getPublicKey(size));
encrypt(cipher, in, os, size);
break;
case PUBKEY_DECRYPT:
cipher.init(Cipher.DECRYPT_MODE, getPublicKey(size));
decrypt(cipher, in, os, size);
break;
case PRIKEY_ENCRYPT:
cipher.init(Cipher.ENCRYPT_MODE, getPrivateKey(size));
encrypt(cipher, in, os, size);
break;
case PRIKEY_DECRYPT:
cipher.init(Cipher.DECRYPT_MODE, getPrivateKey(size));
decrypt(cipher, in, os, size);
break;
}
}
/_加密_/
private static void encrypt(Cipher cipher, InputStream in, OutputStream os,
KeySize size) throws Exception{
byte[] buf = new byte[size.value()/8-11];
int len = 0;
while ((len = in.read(buf)) != -1) {
os.write(cipher.doFinal(buf, 0, len));
}
}
/_解密_/
private static void decrypt(Cipher cipher, InputStream in, OutputStream os,
KeySize size) throws Exception{
byte[] buf = new byte[size.value()/8];
while (in.read(buf) != -1) {
os.write(cipher.doFinal(buf));
}
}

/_获取公钥Cipher_/
private static PublicKey getPublicKey(KeySize size) throws Exception  {
byte[] keyBytes = Base64.decodeBase64(getPublicKeyString(size));
X509EncodedKeySpec keySpec = new X509EncodedKeySpec(keyBytes);
KeyFactory keyFactory = KeyFactory.getInstance("RSA");
PublicKey publicKey = keyFactory.generatePublic(keySpec);
return publicKey;
}
/_获取私钥_/
private static PrivateKey getPrivateKey(KeySize size) throws Exception {
byte[] keyBytes = Base64.decodeBase64(getPrivateKeyString(size));
PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(keyBytes);
KeyFactory keyFactory = KeyFactory.getInstance("RSA");
PrivateKey privateKey = keyFactory.generatePrivate(keySpec);
return privateKey;
}
/\* 生成公私钥 */
public static void generateKeyPair(KeySize size) throws Exception {
SecureRandom secureRandom = new SecureRandom();
KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
keyPairGenerator.initialize(size.value(), secureRandom);
keyPairGenerator.initialize(size.value());
KeyPair keyPair = keyPairGenerator.generateKeyPair();
Key publicKey = keyPair.getPublic();
Key privateKey = keyPair.getPrivate();
System.out.println("publickey:");
char[] pubKey =
Base64.encodeBase64String(publicKey.getEncoded()).toCharArray();
for (int i=0; i<pubKey.length; i++){
System.out.print(pubKey[i]);
if (i % 64 == 63){
System.out.println();
}
}
System.out.println();
System.out.println("privatekey:");
char[] priKey =
Base64.encodeBase64String(privateKey.getEncoded()).toCharArray();
for (int i=0; i<priKey.length; i++){
System.out.print(priKey[i]);
if (i % 64 == 63){
System.out.println();
}
}
System.out.println();
}

}

2015-12-03 18:09 GMT+08:00 zhaijian notifications@github.com:

**Comment by qyxing** [comment]
抱歉，这消息是发到gmail邮箱，因为国内被墙，我的常用邮箱已经更换了，可是github仍然把消息发送的到gmail邮箱

2015-12-03 18:09 GMT+08:00 zhaijian notifications@github.com:

**Comment by zhaijian** [comment]
谢谢您的回复，我这边现在用的方式是服务端私钥签名，客户端公钥验证的机制，签名的方法使用的是谷歌官方的方法SignPKCS1v15，这个问题已经解决了。

**Comment by qyxing** [comment]
好的，这个签名方法，长度有限制，如果有长度超过block的长度的话，是需要另外方法的

------------------ 原始邮件 ------------------
发件人: "zhaijian";notifications@github.com;
发送时间: 2015年12月14日(星期一) 上午10:11
收件人: "caobohua/ostar"ostar@noreply.github.com; 
抄送: "曹柏华"bohua.cao@qq.com; 
主题: Re: [ostar] 使用是出现的问题 (#1)

谢谢您的回复，我这边现在用的方式是服务端私钥签名，客户端公钥验证的机制，签名的方法使用的是谷歌官方的方法SignPKCS1v15，这个问题已经解决了。

**Comment by zhaijian** [comment]
您的意思是签名的长度是有限制的？请问这个长度最大是多少呢

**Comment by qyxing** [comment]
是密钥的长度/8-11

------------------ 原始邮件 ------------------
发件人: "zhaijian";notifications@github.com;
发送时间: 2015年12月14日(星期一) 上午10:26
收件人: "caobohua/ostar"ostar@noreply.github.com; 
抄送: "曹柏华"bohua.cao@qq.com; 
主题: Re: [ostar] 使用是出现的问题 (#1)

您的意思是签名的长度是有限制的？请问这个长度最大是多少呢

**Comment by zhaijian** [comment]
我们测了下，现在的长度能够满足当前的业务，谢谢您的帮助。
