### ISSUE TITLE
参考你的代码，发现一个问题

### ISSUE THREAD

**Issue by ethan-xiao** [caobohua/ostar#2]
参考你的代码，在给比较长的数据加解密时有问题，原因是out Writer在创建时给出了k个为0的字节作为初始值，导致加解密的结果多个K个字节，我改成out = new(bytes.Buffer)就没有问题了。

**Comment by qyxing** [comment]
可以再描述得清楚一点吗？   如果大于K个， 会拆成多个块去加密

**Comment by qyxing** [comment]
多谢反馈
